<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Other Income Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        
        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        
        .report-info {
            font-size: 12px;
            color: #666;
        }
        
        .report-details {
            margin-bottom: 20px;
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }
        
        .report-details table {
            width: 100%;
            border-collapse: collapse;
        }
        
        .report-details td {
            padding: 5px 10px;
            border: none;
        }
        
        .report-details td:first-child {
            font-weight: bold;
            width: 150px;
        }
        
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        .data-table th,
        .data-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        .data-table th {
            background-color: #f8f9fa;
            font-weight: bold;
            text-align: center;
        }
        
        .data-table td:last-child {
            text-align: right;
        }
        
        .total-row {
            background-color: #e9ecef;
            font-weight: bold;
        }
        
        .total-row td:last-child {
            text-align: right;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }
        
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ $company->name ?? 'Company Name' }}</div>
        <div class="report-title">OTHER INCOME REPORT</div>
        <div class="report-info">
            @if($startDate === $endDate)
                As at: {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}
            @else
                Period: {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}
            @endif
            | Basis: {{ ucfirst($reportingType) }}
        </div>
    </div>
    
    <div class="report-details">
        <table>
            <tr>
                <td>Company:</td>
                <td>{{ $company->name ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Branch:</td>
                <td>{{ $branchName }}</td>
            </tr>
            <tr>
                <td>Report Period:</td>
                <td>
                    @if($startDate === $endDate)
                        {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}
                    @else
                        {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}
                    @endif
                </td>
            </tr>
            <tr>
                <td>Reporting Basis:</td>
                <td>{{ ucfirst($reportingType) }}</td>
            </tr>
            <tr>
                <td>Generated By:</td>
                <td>{{ $generatedBy }}</td>
            </tr>
            <tr>
                <td>Generated At:</td>
                <td>{{ $generatedAt }}</td>
            </tr>
        </table>
    </div>
    
    @if(count($otherIncomeData) > 0)
        <table class="data-table">
            <thead>
                <tr>
                    <th>Account Code</th>
                    <th>Account Name</th>
                    <th>Account Group</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $totalIncome = 0;
                @endphp
                @foreach($otherIncomeData as $account)
                    @php
                        $totalIncome += $account['sum'];
                    @endphp
                    <tr>
                        <td>{{ $account['account_code'] }}</td>
                        <td>{{ $account['account'] }}</td>
                        <td>{{ $account['group_name'] }}</td>
                        <td>{{ number_format($account['sum'], 2) }}</td>
                    </tr>
                @endforeach
                <tr class="total-row">
                    <td colspan="3"><strong>Total Other Income</strong></td>
                    <td><strong>{{ number_format($totalIncome, 2) }}</strong></td>
                </tr>
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666;">
            <p>No other income data found for the selected criteria.</p>
        </div>
    @endif
    
    <div class="footer">
        <p>This report was generated on {{ $generatedAt }} by {{ $generatedBy }}.</p>
        <p>Report covers other income accounts excluding sales revenue for the period {{ $startDate }} to {{ $endDate }}.</p>
    </div>
</body>
</html>
